### ISSUE TITLE
Have you tried to make the speedometer live?

### ISSUE THREAD

**Issue by 4rzumanyan** [nglauber/JetpackComposePlayground#3]
Is it possible to make the speedometer work more than once, but when the state changes, like a real car speedometer?

**Comment by nglauber** [comment]
@4rzumanyan if you do the change below, the speedometer will react in according to the `Slider`.
```
@Composable
fun SpeedometerScreen() {
    var targetValue by remember {
        mutableStateOf(0f)
    }
    val speed by remember {
        derivedStateOf {
            (targetValue * 55).toInt()
        }
    }
    //...
    Speedometer(speed) // << use the new state
} 
```
<img src="https://user-images.githubusercontent.com/6018094/188218066-80d30746-cce0-4d6f-b796-0d5d8485f132.gif" width=300 />

**Comment by 4rzumanyan** [comment]
Thank you @nglauber, I already did that using "animateFloatAsState."
